services:
  - type: web
    name: trading-journal-web
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate --schema=packages/database/prisma/schema.prisma && npm run build --workspace=@repo/database && npm run build --workspace=trading-journal && npx prisma migrate deploy --schema=packages/database/prisma/schema.prisma
    startCommand: npm run start --workspace=trading-journal
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
